version: "3.9"
services:
  api:
    build:
      context: ./services/api/
      dockerfile: Dockerfile
    ports:
      - "2080:80"
    environment:
      - port=80
  app:
    build:
      context: ./services/app/
      dockerfile: Dockerfile
    ports: 
      - "1080:80"
  server:
    ports:
      - "80:80"
      - "443:443"
    build:
      context: ./services/server/
      dockerfile: Dockerfile
    depends_on:
      - app
      - api
