version: "3.9"
services:
  api:
    build:
      context: ./services/api/
      dockerfile: Dockerfile
    ports:
      - "2080:80"
    environment:
      - PORT=80
  app:
    build:
      context: ./services/app/
      dockerfile: Dockerfile
    ports: 
      - "1080:80"
  server:
    ports:
      - "80:80"
      - "443:443"
    build:
      context: ./services/server/
      dockerfile: Dockerfile
    environment:
      - PORT=80
      - FRONTEND_HOST="app:80"
      - BACKEND_HOST="api:80"
    depends_on:
      - app
      - api
  database:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: coffee
    ports:
      - 5432:5432
    
  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 3080:8080